### ISSUE TITLE
readmeでのhexキーマップが被っている

### ISSUE THREAD

**Issue by unnamed-hiro** [takashicompany/qmk_firmware#22]
FF外から申し訳ございません
takashicompanyさんのファームウェアreadmeのhexキーコードの説明がかぶりが多くて教えていただくことできないでしょうか？
被りが複数あってどれがしきい値の減少かわからなくて...

**Comment by takashicompany** [comment]
@unnamed-hiro 
すみません、こちら更新してみましたのでよろしければ試してみてください。
だいぶお待たせしまって恐縮です。
